countries = {
    "Malaysia": { "continent": "Asia", "iso_alpha": "MY", "iso_num": 458 },
    "China": { "continent": "Asia", "iso_alpha": "CHN", "iso_num": 156 },
    "Korea": { "continent": "Asia", "iso_alpha": "KOR", "iso_num": 410 },
    "Japan": { "continent": "Asia", "iso_alpha": "JPN", "iso_num": 392 },
    "Morocco": { "continent": "Africa", "iso_alpha": "MAR", "iso_num": 504 },
    "Bolivia": { "continent": "Americas", "iso_alpha": "BOL", "iso_num": 68 }, 
    "Australia" : { "continent": "Oceania", "iso_alpha": "AUS", "iso_num": 36 }, 
    "Singapore" : { "continent": "Asia", "iso_alpha": "SGP", "iso_num": 702 }, 
    "Vietnam" : { "continent": "Asia", "iso_alpha": "VNM", "iso_num": 704 }, 
    "Cambodia": { "continent": "Asia", "iso_alpha": "KHM", "iso_num": 116 }, 
    "Indonesia": { "continent": "Asia", "iso_alpha": "IDN", "iso_num": 360 }, 
    "United Kingdom": { "continent": "Europe", "iso_alpha": "GBR", "iso_num": 826 }, 
    "United States": { "continent": "Americas", "iso_alpha": "USA", "iso_num": 840 },
    "Spain": { "continent": "Europe", "iso_alpha": "ESP", "iso_num": 724 },
    "Malawi": { "continent": "Africa", "iso_alpha": "MWI", "iso_num": 454 },
    "Lebanon": { "continent": "Asia", "iso_alpha": "LBN", "iso_num": 422 },
    "Argentina": { "continent": "Americas", "iso_alpha": "ARG", "iso_num": 32 },
    "Finland": { "continent": "Europe", "iso_alpha": "FIN", "iso_num": 246 },
    "France": { "continent": "Europe", "iso_alpha": "FRA", "iso_num": 250 },
}